### ISSUE TITLE
e2e tests are failing, but not causing the build to fail

### ISSUE THREAD

**Issue by illume** [headlamp-k8s/headlamp#1752]
- [ ] There's 3 of 9 end to end tests failing.
- [ ] CI is not failing when there are test failures

Here's one of the failures...
https://github.com/headlamp-k8s/headlamp/actions/runs/8080804868/job/22077991521?pr=1751#step:11:1096

```ts

  1) [chromium] › headlamp.spec.ts:18:1 › headlamp is there and so is minikube =====================

    Error: expect(received).toHaveTitle(expected)

    Expected pattern: /Token/
    Received string:  "Cluster"
    Call log:
      - expect.toHaveTitle with timeout 5000ms
      - waiting for selector ":root"
      -   selector resolved to <html lang="en">…</html>
      -   unexpected value "Login"
      -   selector resolved to <html lang="en">…</html>
      -   unexpected value "Login"
      -   selector resolved to <html lang="en">…</html>
      -   unexpected value "Cluster"


       at headlampPage.ts:33

      31 |
      32 |   async hasTitleContaining(pattern: RegExp) {
    > 33 |     await expect(this.page).toHaveTitle(pattern);
         |                             ^
      34 |   }
      35 |
      36 |   async hasToken(token: string) {

        at HeadlampPage.hasTitleContaining (/home/runner/work/headlamp/headlamp/e2e-tests/tests/headlampPage.ts:33:29)
        at HeadlampPage.authenticate (/home/runner/work/headlamp/headlamp/e2e-tests/tests/headlampPage.ts:10:10)
        at /home/runner/work/headlamp/headlamp/e2e-tests/tests/headlamp.spec.ts:21:3

```

**Comment by knrt10** [comment]
Looking into this.

**Comment by knrt10** [comment]
Ok, now the weird thing was locally it is passing, and when the change title to check "Cluster" as well then also some of the tests pass but only some failed. It was happening because sometimes the token is already present, and it takes it directly to cluster home page. Fixing it
