### ISSUE TITLE
Searching doesn't work on linux

### ISSUE THREAD

**Issue by veyselsahin** [headlamp-k8s/headlamp#2558]
## Describe the bug
Search in logs via xterm doesn't work due to
```
chunk-DSUIPI7G.js?v=bde2e788:10628 Uncaught Error: You must set the allowProposedApi option to true to use proposed API
    at d._checkProposedApi (@xterm_xterm.js?v=bde2e788:5944:79)
    at d.registerDecoration (@xterm_xterm.js?v=bde2e788:6064:25)
    at n._createResultDecoration (@xterm_addon-search.js?v=bde2e788:322:27)
    at n._highlightAllMatches (@xterm_addon-search.js?v=bde2e788:145:31)
    at n.findNext (@xterm_addon-search.js?v=bde2e788:133:168)
    at handleFindNext (LogViewer.tsx:303:29)
    at handleInputKeyDown (LogViewer.tsx:333:9)
    at HTMLUnknownElement.callCallback2 (chunk-DSUIPI7G.js?v=bde2e788:10552:22)
    at Object.invokeGuardedCallbackDev (chunk-DSUIPI7G.js?v=bde2e788:10577:24)
    at invokeGuardedCallback (chunk-DSUIPI7G.js?v=bde2e788:10611:39)
```
## To Reproduce
Steps to reproduce the bug:
1. Go to pods
2. Select a pod
3. Navigate logs and try to search
4. There error is in the console.

## Environment (please provide info about your environment):
 - dev installation via `npm start`

## Are you able to fix this issue?
Yes (I will propose a PR) 
> Do you want to help fix this issue? Please see our [contribution docs](https://headlamp.dev/docs/latest/contributing). For any non-trivial contributions, we advise you to join our [our slack channel](https://kubernetes.slack.com/messages/headlamp) to discuss the implementation with Headlamp's core developers.

## Additional Context
I tried one solution, and it's working now. 
https://github.com/xtermjs/xterm.js/blob/41e8ae395937011d6bf6c7cb618b851791aed395/src/browser/public/Terminal.ts#L67
https://github.com/xtermjs/xterm.js/blob/41e8ae395937011d6bf6c7cb618b851791aed395/src/common/services/OptionsService.ts#L43

**Comment by joaquimrocha** [comment]
Thanks @veyselsahin . We will take a look.
